### ISSUE TITLE
Activation size mismatch

### ISSUE THREAD

**Issue by narinearraul** [apache/incubator-openwhisk-package-alarms#88]
<img width="783" alt="screen shot 2017-08-31 at 3 04 29 pm" src="https://user-images.githubusercontent.com/2958046/29943245-72502d76-8e5e-11e7-850d-f0f6b4ccae1a.png">

**Comment by bvennam** [comment]
Debugging with @csantanapr today, and discovered the following:
the triggers seem to be firing fine:
"start": 1504294151531,
"start": 1504294150529,
"start": 1504294149526,
"start": 1504294148527,
"start": 1504294147524,
"start": 1504294146523,
"start": 1504294145520,
"start": 1504294144524,
They're all about 1000 ms apart.
We need additional information to debug -- we need to know what time the activation list was pulled, and how that relates to the trigger fires in order to understand further.  

The test needs to be modified so that triggerName and timestamps are given when polling for activations.

**Comment by csantanapr** [comment]
In the logs for the alarm trigger provider the trigger was deleted using the normal path.

**Comment by csantanapr** [comment]
One theory is that activations took longer to show up in the query view for activations. in list since now OpenWhisk is using `stale=ok` for view queries https://github.com/apache/incubator-openwhisk/pull/2632

**Comment by jasonpet** [comment]
@csantanapr - this can be closed
